### ISSUE TITLE
exception when executing tool

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/USFM-Tools#10]
The below error occurred after pulling and running with changes from #8 
.
```
python /var/www/vhosts/door43.org/USFM-Tools/transform.py --target=usx --usfmDir=/var/www/vhosts/api.unfoldingword.org/httpdocs/ulb/txt/1/ulb-en/ --builtDir=/tmp/ulb/ --fileByBook
Traceback (most recent call last):
  File "/var/www/vhosts/door43.org/USFM-Tools/transform.py", line 12, in <module>
    import readerise
  File "/var/www/vhosts/door43.org/USFM-Tools/support/readerise.py", line 5, in <module>
    import parseUsfm
  File "/var/www/vhosts/door43.org/USFM-Tools/support/parseUsfm.py", line 53, in <module>
    cl      = usfmToken(u"cl", phrase)
TypeError: usfmToken() takes exactly 1 argument (2 given)

```

**Comment by kbuildsyourdotcom** [comment]
Fixed in #11
